version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8 
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - ls -R
      - mkdir -p tests/resources
      - mv resources/* tests/resources/
      - robot -d results tests/apiTests.robot

artifacts:
  files:
    - results/**
